In [2]:
import numpy as np
import pandas as pd
import networkx as nx
from networkx.exception import NetworkXError
from cumulative_divrank import cum_divrank

In [3]:
G = nx.DiGraph(nx.path_graph(5))
res_cdrnk = cum_divrank(G, alpha=0.25, d=0.85, personalization=None,
            max_iter=1000, tol=1.0e-6, nstart=None, weight='weight',
            dangling=None)
res_cdrnk

original graph:
[[0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 0.]]


weighted graph:
[[0.  1.  0.  0.  0. ]
 [0.5 0.  0.5 0.  0. ]
 [0.  0.5 0.  0.5 0. ]
 [0.  0.  0.5 0.  0.5]
 [0.  0.  0.  1.  0. ]]


weighted graph with self-link:
[[0.75  0.25  0.    0.    0.   ]
 [0.125 0.75  0.125 0.    0.   ]
 [0.    0.125 0.75  0.125 0.   ]
 [0.    0.    0.125 0.75  0.125]
 [0.    0.    0.    0.25  0.75 ]]


list of dangling nodes:  []


sum of cumulative divrank:  1.0


cumulative divrank:


{0: 0.0528365392513862,
 1: 0.37399779945139133,
 2: 0.1432052020015548,
 3: 0.37766654242438635,
 4: 0.05229391687128137}

In [4]:
G = nx.DiGraph(nx.path_graph(5))
# personalization = {0: 1, 1: 10, 2: 1, 3: 2, 4: 2}
personalization = None
dangling = {0: 1, 1: 10, 2: 1, 3: 2, 4: 2}
# dangling = None
res_cdrnk = cum_divrank(G, alpha=0.75, d=0.85, personalization=personalization,
            max_iter=500, tol=1.0e-6, nstart=None, weight='weight',
            dangling=dangling)
res_cdrnk

original graph:
[[0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 0.]]


weighted graph:
[[0.  1.  0.  0.  0. ]
 [0.5 0.  0.5 0.  0. ]
 [0.  0.5 0.  0.5 0. ]
 [0.  0.  0.5 0.  0.5]
 [0.  0.  0.  1.  0. ]]


weighted graph with self-link:
[[0.25  0.75  0.    0.    0.   ]
 [0.375 0.25  0.375 0.    0.   ]
 [0.    0.375 0.25  0.375 0.   ]
 [0.    0.    0.375 0.25  0.375]
 [0.    0.    0.    0.75  0.25 ]]


list of dangling nodes:  []


sum of cumulative divrank:  1.0


cumulative divrank:


{0: 0.054122402879678,
 1: 0.22471895531194525,
 2: 0.3974904917183342,
 3: 0.26475576558010894,
 4: 0.05891238450993347}

In [5]:
G = nx.DiGraph(nx.path_graph(5))
personalization = {0: 1, 1: 10, 2: 1, 3: 2, 4: 2}
# personalization = None
dangling = {0: 1, 1: 10, 2: 1, 3: 2, 4: 2}
# dangling = None
res_cdrnk = cum_divrank(G, alpha=0.25, d=0.85, personalization=personalization,
            max_iter=1000, tol=1.0e-6, nstart=None, weight='weight',
            dangling=dangling)
res_cdrnk

original graph:
[[0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 0.]]


weighted graph:
[[0.  1.  0.  0.  0. ]
 [0.5 0.  0.5 0.  0. ]
 [0.  0.5 0.  0.5 0. ]
 [0.  0.  0.5 0.  0.5]
 [0.  0.  0.  1.  0. ]]


weighted graph with self-link:
[[0.75  0.25  0.    0.    0.   ]
 [0.125 0.75  0.125 0.    0.   ]
 [0.    0.125 0.75  0.125 0.   ]
 [0.    0.    0.125 0.75  0.125]
 [0.    0.    0.    0.25  0.75 ]]


list of dangling nodes:  []


sum of cumulative divrank:  0.9999999999999999


cumulative divrank:


{0: 0.012702093007978196,
 1: 0.7264814733104256,
 2: 0.0264556229366311,
 3: 0.1942913866059808,
 4: 0.040069424138984254}

In [6]:
nodes = ['A', 'B', 'C', 'D']
edges = [
    ('A', 'B'),
    ('A', 'C'),
    ('A', 'D'),
    ('B', 'A'),
    ('B', 'D'),
    ('D', 'B'),
    ('D', 'C')
#     ('C', 'C')
]

G = nx.DiGraph()
G.add_nodes_from(nodes)
G.add_edges_from(edges)

In [7]:
personalization = {'A': 1, 'B': 1, 'C': 2, 'D': 5}
# personalization = None
# dangling = {'A': 1, 'B': 1, 'C': 2, 'D': 5}
dangling = None
res_cdrnk = cum_divrank(G, alpha=0.25, d=0.85, personalization=personalization,
            max_iter=1000, tol=1.0e-6, nstart=None, weight='weight',
            dangling=dangling)
res_cdrnk

original graph:
[[0. 1. 1. 1.]
 [1. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 1. 1. 0.]]


weighted graph:
[[0.         0.33333333 0.33333333 0.33333333]
 [0.5        0.         0.         0.5       ]
 [0.         0.         0.         0.        ]
 [0.         0.5        0.5        0.        ]]


weighted graph with self-link:
[[0.75       0.08333333 0.08333333 0.08333333]
 [0.125      0.75       0.         0.125     ]
 [0.         0.         0.75       0.        ]
 [0.         0.125      0.125      0.75      ]]


list of dangling nodes:  []


sum of cumulative divrank:  1.0


cumulative divrank:


{'A': 0.021561459123830683,
 'B': 0.037368822131326425,
 'C': 0.6990605319676008,
 'D': 0.2420091867772421}